### ISSUE TITLE
Ha 115.2 update breaks ZHA Map

### ISSUE THREAD

**Issue by ckhyatt** [zha-ng/zha-map#31]
This was working on 115.1 

The map no longer loads. The date in the top left corner is 1970-01-01

Logger: homeassistant
Source: custom_components/zha_map/neighbour.py:131
First occurred: 10:29:07 AM (1 occurrences)
Last logged: 10:29:07 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/zha_map/__init__.py", line 137, in build
    await self.scan_device(seed)
  File "/config/custom_components/zha_map/__init__.py", line 226, in scan_device
    nei = await Neighbour.scan_device(device)
  File "/config/custom_components/zha_map/neighbour.py", line 115, in scan_device
    await r.scan()
  File "/config/custom_components/zha_map/neighbour.py", line 131, in scan
    neighbors = val.NeighborTableList
AttributeError: 'Neighbors' object has no attribute 'NeighborTableList'

**Comment by Derkades** [comment]
Are you using the latest zha-map version? It seems to have already been fixed: https://github.com/zha-ng/zha-map/issues/24

**Comment by bjackson** [comment]
I'm on v0.3.1, and I have the same issue with a ConBee II.
```
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 142, in handle_call_service
    connection.context(msg),
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1315, in async_call
    task.result()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1350, in _execute_service
    await handler.func(service_call)
  File "/home/homeassistant/.homeassistant/custom_components/zha_map/__init__.py", line 66, in scan_now_handler
    await builder.preempt_build()
  File "/home/homeassistant/.homeassistant/custom_components/zha_map/__init__.py", line 125, in preempt_build
    await self.build()
  File "/home/homeassistant/.homeassistant/custom_components/zha_map/__init__.py", line 138, in build
    nei = await Neighbour.scan_device(device)
  File "/home/homeassistant/.homeassistant/custom_components/zha_map/neighbour.py", line 78, in scan_device
    await r.scan()
  File "/home/homeassistant/.homeassistant/custom_components/zha_map/neighbour.py", line 83, in scan
    for neighbor in self.device.neighbors:
AttributeError: 'DeconzDevice' object has no attribute 'neighbors'
```

**Comment by ckhyatt** [comment]
I am also on the Conbee II.

I just installed this last week. Is there a newer version?

Thanks!

**Comment by Adminiuga** [comment]
@ckhyatt for zha_map 0.2.0 and newer, you should be on ha 0.115.2 or newer

**Comment by Adminiuga** [comment]
Zha_map is a custom component and is not supported by ha. 0.3.1 of zha map will be the last version with functionality being moved into ha core zha integration

**Comment by Adminiuga** [comment]
If issue still persiste with ha 0.115.2 and zha map 0.3.1 open an issue in zha map repo
