### ISSUE TITLE
AttributeError: 'Neighbors' object has no attribute 'NeighborTableList'

### ISSUE THREAD

**Issue by rchovan** [zha-ng/zha-map#24]
Hello, 
after upgrade HA to 0.115.2 ZHA scan does not work, and I see this in HA log:

```
2020-09-21 13:54:46 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/zha_map/__init__.py", line 137, in build
    await self.scan_device(seed)
  File "/config/custom_components/zha_map/__init__.py", line 226, in scan_device
    nei = await Neighbour.scan_device(device)
  File "/config/custom_components/zha_map/neighbour.py", line 115, in scan_device
    await r.scan()
  File "/config/custom_components/zha_map/neighbour.py", line 131, in scan
    neighbors = val.NeighborTableList
AttributeError: 'Neighbors' object has no attribute 'NeighborTableList'
2020-09-21 13:54:46 DEBUG (MainThread) [custom_components.zha_map] Building topology starting from coordinator
2020-09-21 13:54:46 DEBUG (MainThread) [custom_components.zha_map.neighbour] [00:21:2e:ff:ff:04:d4:bb]: neighbor request Status: Status.SUCCESS. Response: Neighbors(entries=3, start_index=0, neighbor_table_list=[Neighbor(extended_pan_id=00:21:2e:ff:ff:04:d4:bb, ieee=58:8e:81:ff:fe:6b:1e:10, nwk=0x1208, struct=_NeighborPackStruct(packed=37), permit_joining=<PermitJoins.Accepting: 1>, depth=1, lqi=116), Neighbor(extended_pan_id=00:21:2e:ff:ff:04:d4:bb, ieee=08:6b:d7:ff:fe:07:7e:0d, nwk=0x8ED5, struct=_NeighborPackStruct(packed=37), permit_joining=<PermitJoins.Accepting: 1>, depth=1, lqi=249)])
2020-09-21 13:54:51 INFO (SyncWorker_42) [zoneminder.zm] Initializing runstate 1
```

**Comment by jacktho** [comment]
Same error for me.

```
Logger: homeassistant
Source: custom_components/zha_map/neighbour.py:131
First occurred: 8:22:52 AM (1 occurrences)
Last logged: 8:22:52 AM
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/config/custom_components/zha_map/__init__.py", line 137, in build
    await self.scan_device(seed)
  File "/config/custom_components/zha_map/__init__.py", line 226, in scan_device
    nei = await Neighbour.scan_device(device)
  File "/config/custom_components/zha_map/neighbour.py", line 115, in scan_device
    await r.scan()
  File "/config/custom_components/zha_map/neighbour.py", line 131, in scan
    neighbors = val.NeighborTableList
AttributeError: 'Neighbors' object has no attribute 'NeighborTableList'

```

**Comment by Adminiuga** [comment]
Zha_map is currently broken on 115.2 and zigpy. 0.24.x
An interim fix will be out this week. In long run most of zha map will be in zigpy

**Comment by Adminiuga** [comment]
should be fixed by https://github.com/zha-ng/zha-map/pull/25 new release tagged as `0.2.0` 
Can you please give it a try and report?

**Comment by rchovan** [comment]
Hi, fixed with release 0.2.0 , thanks.
